name: Deploy Dev

on:
  workflow_dispatch:
  push:
    branches: [cf-development]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      OCIR_HOST: ocir.us-ashburn-1.oci.oraclecloud.com
      OCIR_REPO: ocir.us-ashburn-1.oci.oraclecloud.com/idfmutpuhiky/dev-ssr-server

    outputs:
      image_tag: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: cf-development

      - name: Setting up node
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.3

      - name: Install Client Dependencies
        working-directory: ./ui-app/client
        run: npm i

      - name: Setup rClone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.CLOUDFLARE_RCLONE_CONFIG }}

      - uses: cloudposse/github-action-jq@main
        name: Installing jq
        with:
          compact: true
          input: '["test", "test2", "test3"]'
          script: |-
            map(select(. == "test"))

      - name: Generate Component Catalog
        working-directory: ./ui-app/client
        run: npm run generate-catalog

      - name: Building to JS Dev
        working-directory: ./ui-app/client
        run: npm run cf-dev

      - name: Copy manifest for SSR
        run: |
          mkdir -p ui-app/ssr/manifests
          cp ./ui-app/client/dist/asset-manifest.json ui-app/ssr/manifests/asset-manifest.json

      - name: Pushing Dev to Cloudflare
        working-directory: ./ui-app/client
        run: |
          rclone copy ./dist r2user:dev-static/js/dist
          rclone copyto ./component-catalog.json r2user:dev-static/js/component-catalog.json

          echo "\n"
          echo "JSON prepared :"
          find dist -type f | xargs -d '\n' -n 25 | while IFS= read -r batch; do echo "$batch" | tr ' ' '\n' | jq -R -s '{"files": split("\n")[:-1] | map("https://cdn-dev.modlix.com/js/" + .)}'; done

          echo "Calling purge for cdn-dev.modlix.com :"
          find dist -type f | xargs -d '\n' -n 25 | while IFS= read -r batch; do echo "$batch" | tr ' ' '\n' | jq -R -s '{"files": split("\n")[:-1] | map("https://cdn-dev.modlix.com/js/" + .)}' | curl -s https://api.cloudflare.com/client/v4/zones/f8fe46c016fcfdc188401768a0ac7d01/purge_cache --request POST --header "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" --header "Content-Type: application/json"  --data @- ; echo ""; done

      - name: Invalidating Application Server cache
        run: |
          curl -s --header "Authorization: ${{ secrets.NOCODE_TOKEN }}" https://apps.dev.modlix.com/api/ui/newdeployment

      - name: Login to OCIR
        run: |
          echo "${{ secrets.OCI_NON_PROD_CLI_AUTH_TOKEN }}" | docker login $OCIR_HOST \
            -u "${{ secrets.OCI_NON_PROD_DOCKER_USER_NAME }}" \
            --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $OCIR_REPO:${{ github.sha }} \
                       -t $OCIR_REPO:latest \
                       -f ui-app/ssr/Dockerfile .
          docker push $OCIR_REPO:${{ github.sha }}
          docker push $OCIR_REPO:latest

  deploy-ssr:
    needs: build-and-deploy
    runs-on: self-hosted

    steps:
      - name: Deploy to development server
        run: |
          ssh -i /home/ubuntu/keys/dev-internal.key opc@${{ secrets.DEV_SERVER_IP }} \
            "bash /home/opc/scripts/keepup.sh deploy ssr-server ocir.us-ashburn-1.oci.oraclecloud.com/idfmutpuhiky/dev-ssr-server:${{ needs.build-and-deploy.outputs.image_tag }} 2>&1 | tee -a /var/log/keepup.log"

  build-and-upload-local:
    needs: deploy-ssr
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: cf-development

      - name: Setting up node
        uses: actions/setup-node@v4
        with:
          node-version: 21.7.3

      - name: Install Client Dependencies
        working-directory: ./ui-app/client
        run: npm i

      - name: Setup rClone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.CLOUDFLARE_RCLONE_CONFIG }}

      - uses: cloudposse/github-action-jq@main
        name: Installing jq
        with:
          compact: true
          input: '["test", "test2", "test3"]'
          script: |-
            map(select(. == "test"))

      - name: Generate Component Catalog (Local)
        working-directory: ./ui-app/client
        run: npm run generate-catalog

      - name: Building to JS Local
        working-directory: ./ui-app/client
        run: npm run cf-local

      - name: Pushing Local to Cloudflare
        working-directory: ./ui-app/client
        run: |
          rclone copy ./dist r2user:local-static/js/dist
          rclone copyto ./component-catalog.json r2user:local-static/js/component-catalog.json

          echo "\n"
          echo "JSON prepared :"
          find dist -type f | xargs -d '\n' -n 25 | while IFS= read -r batch; do echo "$batch" | tr ' ' '\n' | jq -R -s '{"files": split("\n")[:-1] | map("https://cdn-local.modlix.com/js/" + .)}'; done

          echo "Calling purge for cdn-local.modlix.com :"
          find dist -type f | xargs -d '\n' -n 25 | while IFS= read -r batch; do echo "$batch" | tr ' ' '\n' | jq -R -s '{"files": split("\n")[:-1] | map("https://cdn-local.modlix.com/js/" + .)}' | curl -s https://api.cloudflare.com/client/v4/zones/f8fe46c016fcfdc188401768a0ac7d01/purge_cache --request POST --header "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" --header "Content-Type: application/json"  --data @- ; echo ""; done
